import type { Metadata } from "next";
import { Roboto, Sono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import { twMerge } from "tailwind-merge";
import Script from "next/script";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "react-hot-toast";
import NavbarTop from "@/components/navigation/navbar-top";

const sono = Sono({ subsets: ["latin"] });

const roboto = Roboto({
  weight: ["400", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};
export default async function RootLayout({
                                           children
                                         }: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html
        lang="en"
        className={twMerge(
          sono.className,
          roboto.className
        )}
      >
      <head>
        <title title={"Piguesso"} />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
      </head>
      <body className={"h-screen w-screen bg-background overflow-x-hidden overflow-y-hidden"} draggable={false}>
      <Script
        src="https://kit.fontawesome.com/7dfc9e0334.js"
        crossOrigin="anonymous"
      />
      <ThemeProvider
        attribute="class"
        defaultTheme="dark"
        enableSystem
        disableTransitionOnChange
      >
        <AppRouterCacheProvider>
          <Toaster />
          <NavbarTop />
          {children}
        </AppRouterCacheProvider>
      </ThemeProvider>
      </body>
      </html>
    </ClerkProvider>
  );
}
